### EXP-1. 
#### Develop a python program to read n digit integer number and seperate the integer number and display each digit

In [27]:
n=int(input("enter the number of digits:"))
if n>0:
    number=int(input(f"Enter a {n}-digit integer:"))
    if number>=10**(n-1) and number<10**n:
        for i  in range(n):
         digit=number//(10**(n-1))
         print(digit)
         number%=10**(n-1)
         n-=1
    else:
         print(f'Please enter a {n}-digit integer:')
else:
     print(f" Please enter a valid number of digits(greater than 0).")

enter the number of digits:4
Enter a 4-digit integer:1238
1
2
3
8


## OR

In [10]:
n=int(input("enter the number of digits:"))
if n>0:
    number=int(input(f"Enter a {n}-digit integer:"))
    if len(str(number))==n:
        for i  in range(n):
         digit=number//(10**(n-1))
         print(digit)
         number%=10**(n-1)
         n-=1
    else:
         print(f'Please enter a {n}-digit integer:')
else:
     print(f" Please enter a valid number of digits(greater than 0).")

enter the number of digits:4
Enter a 4-digit integer:8796
8
7
9
6


### EXP-2
#### Develop a python program to accept 4 numbers and display them in sorted order using a minimum number of if else statements

In [7]:
a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
c=int(input("enter the third number:"))
d=int(input("enter the fourth number:"))
if a>b:a,b=b,a
if c>d:c,d=d,c
if a>c:a,c=c,a
if b>d:b,d=d,b
if b>c:b,c=c,b
print("The sorted numbers are:",a,b,c,d)

enter the first number:10
enter the second number:6
enter the third number:9
enter the fourth number:65
The sorted numbers are: 6 9 10 65


#### descending order

In [12]:
a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
c=int(input("enter the third number:"))
d=int(input("enter the fourth number:"))
if a<b:a,b=b,a
if c<d:c,d=d,c
if a<c:a,c=c,a
if b<d:b,d=d,b
if b<c:b,c=c,b
print("The sorted numbers are:",a,b,c,d)

enter the first number:9
enter the second number:78
enter the third number:67
enter the fourth number:10
The sorted numbers are: 78 67 10 9


In [22]:
# and 
10&9

8

In [23]:
# OR
10|9


11

In [24]:
# NOT
~10

-11

In [25]:
#X0R
10^9

3

In [26]:
a=-3


In [36]:
a>>1

6

In [38]:
a=12
a>>2

3

In [41]:
a=-12
a>>2

-3

In [47]:
a>>2


2

In [55]:
a=int(input('enter'))
a=a+20
print(a)

enter3
23


## 3) Develop a program for checking if a given n digit number is palindrome or not


In [1]:
number=int(input("Enter an n-digit number:"))
original_number=number
reversed_number=0
while number>0:
    digit=number%10
    reversed_number=reversed_number*10+digit
    number//=10
if original_number==reversed_number:
    print("Palindrome")
else:
    print("Not Palindrome")
               
            
    



Enter an n-digit number:1221
Palindrome


## 4) Develop a python script to display a multiplication table for a given integer 

In [2]:
n=int(input("enter an integer for multipication table:"))
print(f"multiplication table for {n}:")
for i in range (1,11):
    result= n*i
    print(f"{n}*{i}={result}")
    

enter an integer for multipication table:6
multiplication table for 6:
6*1=6
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
6*10=60


## 5) Develop python scripts to calculate the mean ,median,mode,variance and standard deviation of n integer number

In [5]:
n=int(input("Enter the number of elements:"))
numbers=[int(input(f"Enter number{i+1}:"))for i in range(n)]
#mean
mean=sum(numbers)/n
#median
numbers.sort()
if n%2==0:
    median=(numbers[n//2-1]+numbers[n//2])/2
else:
    median=numbers[n//2]
frequency={num:numbers.count(num)for num in numbers}
max_count=max(frequency.values())
mode=[k for k,v in frequency.items() if v==max_count]
if len(mode)==n:
    mode="no mode"
mean_difference_squared_sum=sum((x-mean)**2 for x in  numbers)
variance_sample=mean_difference_squared_sum/(n-1) if n>1 else 0
variance_population=mean_difference_squared_sum/n
std_deviation_sample=variance_sample**0.5
std_deviation_population=variance_population**0.5
print(f"Mean:{mean}")
print(f"Median:{median}")
print(f"Mode:{mode}")
print(f"sample Variance:{variance_sample}")
print(f"Population Variance:{variance_population}")
print(f"Sample Standard Deviation:{std_deviation_sample}")
print(f"Population Standard Deviation:{std_deviation_population}")

Enter the number of elements:6
Enter number1:4
Enter number2:8
Enter number3:6
Enter number4:5
Enter number5:3
Enter number6:9
Mean:5.833333333333333
Median:5.5
Mode:no mode
sample Variance:5.366666666666667
Population Variance:4.472222222222222
Sample Standard Deviation:2.316606713852541
Population Standard Deviation:2.1147629234082532


In [9]:
D1={'a':10,'b':20,'c':30}
D1
D1.keys()
D1.values()
D1.items()


dict_items([('a', 10), ('b', 20), ('c', 30)])

In [12]:
n=5
while n>0:
    print(n)
    n-=1

    print("loop finished without break:")
    

5
loop finished without break:
4
loop finished without break:
3
loop finished without break:
2
loop finished without break:
1
loop finished without break:


In [2]:
n=5
while n>0:
    print(n)
    if n==3:
        break
    n-=1
else:  
    print("loop finished without break:")
    

5
4
3


In [17]:
n=5
while n>0:
    print(n)
    if n==3:
        break
    n-=1
 
print("loop finished without break:")
    

5
4
3
loop finished without break:


In [22]:
n=range(1,4)
for j in n:
    print("Factorial of "+str(j)+" is")
    mul=1
    for i in range(1,j+1):
        mul=mul*i
        print(mul)

Factorial of 1 is
1
Factorial of 2 is
1
2
Factorial of 3 is
1
2
6


In [20]:
x=[1,2]
y=[4,5]
for i in x:
    for j in y:
        print(i,j)

1 4
1 5
2 4
2 5


## EXp-6

### Develop a python script to rotate right about a given position in that list and display them

In [3]:
number=int(input("Enter the integer number:"))
revs_number=0
while(number>0):
    remainder=number%10
    revs_number=(revs_number*10)+remainder
    number=number//10
print("the reverse number is {}".format(revs_number))

Enter the integer number:-24
the reverse number is 0


## EXP-7

### Develop a python script to interchange the digits of a given integer number

In [6]:
def interchange_digits(number,pos1,pos2):
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int(''.join(number_list))
    return interchanged_number
number=int(input("Enter the user input:"))
pos1=int(input("Enter the 1st position which you want to swap:"))
pos2=int(input("Enter the 2nd position which you want to swap:"))
interchanged_number=interchange_digits(number,pos1,pos2)
print("Original number:",number)
print("Interchanged number:",interchanged_number)

Enter the user input:23456
Enter the 1st position which you want to swap:3
Enter the 2nd position which you want to swap:5
Original number: 23456
Interchanged number: 23654


### program for natural numbers

In [9]:
n=int(input("enter the numbers:"))
i=1
while i<=n:
    print(i,end=" ")
    i+=1

enter the numbers:6
1 2 3 4 5 6 

### program for even numbers

In [11]:
n=int(input("enter the value:"))
i=2
while i <=n:
    print(i,end=" ")
    i+=2

enter the value:8
2 4 6 8 

### program for odd numbers

In [13]:
n=int(input("enter the value:"))
i=1
while i <=n:
    print(i,end=" ")
    i+=2

enter the value:6
1 3 5 

In [29]:
def sum_of_natural_numbers(n):
    return n * (n + 1) // 2
try:
    number = int(input("Enter a positive integer: "))
    if number < 0:
        print("Please enter a positive integer.")
    else:
        result = sum_of_natural_numbers(number)
        print(f"The sum of natural numbers up to {number} is: {result}")
except ValueError:
    print("Invalid input! Please enter a valid positive integer.")


Enter a positive integer: 5
The sum of natural numbers up to 5 is: 15


In [28]:
n = int(input("Enter a natural number: "))
if n >= 0:
    print("Sum:", n * (n + 1) // 2)
else:
    print("Please enter a non-negative number.")


Enter a natural number: 6
Sum: 21


## EXP 8

### Develop a python program to capitalize a given list of strings

In [3]:
def capitalize_strings(string_list):
    return[s.capitalize() for s in string_list]
input_strings=['hello','good','how','simple']
capitalized_strings=capitalize_strings(input_strings)
print(capitalized_strings)

['Hello', 'Good', 'How', 'Simple']


## EXP 9

### Using a dictionary develop a python program to determine and print the number of duplicate words in a sentence


In [2]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={ }
    for word in words:
        word=word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
    duplicates={word:count for word,count in word_count.items() if count >1}
    if duplicates:
        print("Duplicate words and their counts:")
        for word,count in duplicates.items():
            print(f"{word}:{count}")
    else:
        print("no duplicate words found ")
sentence=input("enter a sentence:")
count_duplicate_words(sentence)

enter a sentence:my name is pavan and my branch name is aiml
Duplicate words and their counts:
my:2
name:2
is:2


## EXP-10

### Develop a python program to read Numpy array and print row (sum,mean,standard deviation) and column(row,mean,standard deviation)

In [5]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("Numpy Array")
print(data)
print("____________________")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("Row Sum")
print(totalr)
print("Column Sum")
print(totalc)
print("____________________")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("Row Mean")
print(meanr)
print("Column Mean")
print(meanc)
print("____________________")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("Row Standard Deviation")
print(stdr)
print("Column Standard Deviation")
print(stdc)

Numpy Array
[[1 2 3]
 [4 5 6]]
____________________
Row Sum
[ 6 15]
Column Sum
[5 7 9]
____________________
Row Mean
[2. 5.]
Column Mean
[2.5 3.5 4.5]
____________________
Row Standard Deviation
[0.81649658 0.81649658]
Column Standard Deviation
[1.5 1.5 1.5]
